version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: my_redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=mysecretpassword
    command: ["redis-server", "--requirepass", "mysecretpassword"]
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local
